### ISSUE TITLE
Generation fails with "cannot write to file: bad file descriptor"

### ISSUE THREAD

**Issue by Eternal2008** [SleipnirGroup/Choreo#354] opened 2024-02-29 01:09 UTC
When generating new path it returns an infeasible error. It has an unknown trigger and happens seemingly at random even on newly created paths with just 2 waypoints and nothing else.

**Comment by calcmogul** [comment] 2024-02-29 01:14
These spurious infeasible trajectory errors have been fixed on main by switching to a different optimizer backend. Please try one of the builds here: https://github.com/SleipnirGroup/Choreo/actions/runs/8084712732

**Comment by Eternal2008** [comment] 2024-02-29 01:26
Thanks for the suggestion now it says Bad file reference when attempting to generate the paths for any new paths I create, but not for any old ones I created. Those I can just regenerate without any issues.

**Comment by calcmogul** [comment] 2024-02-29 01:41
It may have been caused by a recent upgrade to the fs package. Try this build once it's finished: https://github.com/calcmogul/Choreo/actions/runs/8089723596

**Comment by Eternal2008** [comment] 2024-02-29 01:56
Ok now the first generation i run causes this 
![Screenshot 2024-02-28 195523](https://github.com/SleipnirGroup/Choreo/assets/122846197/08014d09-b466-4d62-90e8-ea443bbab99f)
and upon re attempting generation it goes back to saying their is a bad file descriptor
![Screenshot 2024-02-28 195546](https://github.com/SleipnirGroup/Choreo/assets/122846197/c062fdaf-51fc-4f8d-b121-0b85c76e5e30)

**Comment by calcmogul** [comment] 2024-03-01 01:56
This error message is from fmtlib during a write failure. I'll work on a patch for Sleipnir.

**Closed** 2024-03-01 03:18 UTC
