### ISSUE TITLE
[choreo] change wording for project management buttons

### ISSUE THREAD

**Issue by oh-yes-0-fps** [SleipnirGroup/Choreo#616] opened 2024-08-30 04:18 UTC
![image](https://github.com/user-attachments/assets/52e75666-26dd-42bf-a092-2b74fddb21b1)

This usage of `File` should be replaced with `Project`, the `File` wording can make it confusing if its talking about a trajectory or .chor to new users.

**Comment by spacey-sooty** [comment] 2024-09-02 02:47
Partial duplicate of https://github.com/SleipnirGroup/Choreo/issues/610

**Closed** 2024-09-02 19:24 UTC
Labels: type: enhancement, component: ui
